minor/feature/UBI-494-StatsCharacters
Ubivius/microservice-character-data pull request #27
Opened 2021-11-09 00:17 UTC by MaximeStOnge

#### What changes does this PR contain?
- Characters stats 
- Call for characters alive

#### Which JIRA ticket ID's are associated with this PR?
UBI-494 

#### Additional comments and information

2021-11-09 13:20 UTC, ArcticWalrus requested changes
Also missing at least a couple of unit tests for when the user has one, several or no alive characters

2021-11-09 13:20 UTC, ArcticWalrus commented on pkg/database/db_interface.go
> +	GetCharactersAliveByUserID(ctx context.Context, userID string) (data.Characters, error)
GetAliveCharactersByUserID?

2021-11-09 13:20 UTC, ArcticWalrus commented on pkg/database/mockDB.go
> +func (mp *MockCharacters) GetCharactersAliveByUserID(ctx context.Context, userID string) (data.Characters, error) {
GetAliveCharactersByUserID?

2021-11-09 13:20 UTC, ArcticWalrus commented on pkg/handlers/get.go
> +func (characterHandler *CharactersHandler) GetCharactersAliveByUserID(responseWriter http.ResponseWriter, request *http.Request) {
GetAliveCharactersByUserID?

2021-11-10 01:47 UTC, JeremiSavard approved these changes

2021-11-10 14:27 UTC, ArcticWalrus commented
> 
> 
> Also missing at least a couple of unit tests for when the user has one, several or no alive characters

Il ne manque que quelques tests dans handlers_test.go en utilisant la mock DB

2021-11-15 13:50 UTC, ArcticWalrus requested changes

2021-11-15 13:50 UTC, ArcticWalrus commented on pkg/handlers/get.go
> +func (characterHandler *CharactersHandler) GetAliveCharactersByUserID(responseWriter http.ResponseWriter, request *http.Request) {
Missing test updates and new tests for handlers

2021-11-16 13:30 UTC, ArcticWalrus approved these changes

2021-11-17 19:24 UTC, merged