Refactor & finishing first iteration of Character-Data microservice
Ubivius/microservice-character-data pull request #6
Opened 2021-03-22 14:27 UTC by ArtiKitten

#### What changes does this PR contain?
First iteration of Character-Data refactored from template changes
#### Which JIRA ticket ID's are associated with this PR?
UBI-337
#### Does this PR change the outward facing API?
Yes
#### Additional comments and information
Some tests were added since the first iteration. There is still some tests to add when it'll talk to the User Microservice to validate that a user exists. It still uses fake DB and int id for the data. We'll need to talk about what kind of character name we allow to edit the validation regex to fit our conditions.
@ubivius/microservices

2021-03-22 16:58 UTC, ArcticWalrus requested changes

2021-03-22 16:58 UTC, ArcticWalrus commented on README.md
> +## TODO
remove todo

2021-03-22 16:58 UTC, ArcticWalrus commented on chart/templates/NOTES.txt
> +Thank you for installing {{ .Chart.Name }}.
Do a search for all mentions of microservice-template and replace with the correct name

2021-03-22 16:58 UTC, ArcticWalrus commented on data/characters.go
> +// Formatting done with json tags to the right. "-" : don't include when encoding to json
Remove comment about json tags

2021-03-22 16:58 UTC, ArcticWalrus commented on data/characters.go
> +	characterList = append(characterList[:index], characterList[index+1])
Fix delete as in microservice-template

2021-03-22 16:58 UTC, ArcticWalrus commented on data/json.go
> +func FromJSON(i interface{}, reader io.Reader) error {
Remove From and To JSON

2021-03-22 16:58 UTC, ArcticWalrus commented on handlers/middleware.go
> +// Errors should be templated in the future.
Remove this comment from non microservice-template repo

2021-03-22 16:58 UTC, ArcticWalrus commented on main.go
> +	signal.Notify(signalChannel, os.Interrupt)
These linting errors are fixed in microservice-template

2021-03-22 16:58 UTC, ArcticWalrus commented on pkg/data/characters.go
> +// Formatting done with json tags to the right. "-" : don't include when encoding to json
Same thing for comment here

2021-03-22 16:58 UTC, ArcticWalrus commented on pkg/data/characters.go
> +	characterList = append(characterList[:index], characterList[index+1])
Fix delete

2021-03-22 16:58 UTC, ArcticWalrus commented on pkg/data/json.go
> +// FromProductJSON deserializes the interface from JSON string
Same file twice. Why do we have json in pkg and data

2021-03-22 16:58 UTC, ArcticWalrus commented on pkg/server/server.go
> +package server
We can remove this package until the refactor is actually done in microservice-template

2021-03-22 16:58 UTC, ArcticWalrus commented on scripts/elasticsearch.sh
> +#!/bin/bash
This script is useless here. We can remove it

2021-03-24 14:04 UTC, ArtiKitten commented on pkg/data/json.go
> +// FromProductJSON deserializes the interface from JSON string
Pour une raison obscure, après avoir modifier le format pour avoir pkd/data, pkg/handlers, etc. Je n'ai pas delete les dossiers originaux.

2021-03-24 14:29 UTC, ArtiKitten commented on chart/templates/NOTES.txt
> +Thank you for installing {{ .Chart.Name }}.
Selon @MaximeStOnge, il faudrait une autre tâche pour setup les charts pour le déploiement

2021-03-24 14:42 UTC, ArtiKitten commented on main.go
> +	signal.Notify(signalChannel, os.Interrupt)
What should I do about this?

2021-03-25 15:14 UTC, MaximeStOnge requested changes

2021-03-25 15:14 UTC, MaximeStOnge commented on pkg/router/router.go
> +	// Mux route handling with gorilla/mux
Duplicate comment

2021-03-25 15:14 UTC, MaximeStOnge commented on pkg/data/characters.go
> +var ErrorCharacterNameAlreadyExist = fmt.Errorf("Character name is already used")
Est-ce qu'on veut vraiment que les noms de personnage soit unique?

2021-03-25 15:14 UTC, MaximeStOnge commented on pkg/handlers/handlers_test.go
> +func TestUpdateCharacter(t *testing.T) {
Il faudrait un TestUpdateNonExistantCharacter

2021-03-25 17:23 UTC, ArtiKitten commented on pkg/data/characters.go
> +var ErrorCharacterNameAlreadyExist = fmt.Errorf("Character name is already used")
À discuter avec les autres. Au pire, on l'enlèvera, ce n'est pas un problème.

2021-03-28 15:30 UTC, MaximeStOnge approved these changes

2021-03-30 16:30 UTC, ArcticWalrus commented on main.go
> +	signal.Notify(signalChannel, os.Interrupt)
https://github.com/Ubivius/microservice-template/blob/master/cmd/microservice-template/main.go#L69
and under

2021-03-30 16:31 UTC, ArcticWalrus requested changes

2021-03-30 16:31 UTC, ArcticWalrus commented on README.md
> +Beginning of code was based off of Nic Jackson's building microservices in Go : https://www.youtube.com/playlist?list=PLmD8u-IFdreyh6EUfevBcbiuCKzFk0EW_
Remove Nic Jackson reference

2021-04-04 14:05 UTC, ArcticWalrus approved these changes

2021-04-04 14:05 UTC, merged